# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C version of the VSEM model
#' @param par parameter vector
#' @param PAR 	Photosynthetically active radiation (PAR) MJ /m2 /day
#' @export
v3semC <- function(par, PAR) {
    .Call('PMCMC_v3semC', PACKAGE = 'PMCMC', par, PAR)
}

